### ISSUE TITLE
Cannot find sample data 0psDataGen.spl for the book

### ISSUE THREAD

**Issue by ndestor** [PacktPublishing/Splunk-Operational-Intelligence-Cookbook-Third-Edition#1]
Hello,

Can you provide the sample data required for this third version of your book? I tried with the sample data available for the second version but one file is missing (hvac_log).

Thanks in advance,
Nicolas

**Comment by techsachinkumar** [comment]
Hi @ndestor 

Code files for the book has been added. 
Please refer to Chapter01 for the sample data.

Regards
